language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
branches:
  only:
    - master
    - 3.4

before_script: utils/install_llvm.sh 3.4
script: utils/build.sh

notifications:
  recipients:
    - liuml07+update@gmail.com
  email:
    on_success: change
    on_failure: always
