language: cpp

compiler:
  - clang
  - gcc

os: linux

env: LLVM_HOME=$HOME/llvm BuildMode=Release+Asserts

script:
  - sudo -E utils/install_llvm.sh
  - utils/build.sh

cache:
  directories:
    - $HOME/llvm

notifications:
  recipients:
    - liuml07+update@gmail.com
  email:
    on_success: change
    on_failure: always
