language: cpp

compiler:
  - clang
  - gcc

os: linux

env: LLVM_HOME=$HOME/llvm BuildMode=Release+Asserts

before_script: sudo utils/install_llvm.sh
script: utils/build.sh

cache:
  directories:
    - $HOME/llvm

notifications:
  recipients:
    - liuml07+update@gmail.com
  email:
    on_success: change
    on_failure: always
